# Informations générales

sonar.projectKey=Nesesan_Projet_OC10
sonar.organization=nesesan
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.projectName=Projet_OC10
sonar.projectVersion=1.0

# BACK-END (Java)

sonar.sources=back/src
sonar.tests=back/src/test
sonar.java.binaries=back/target/classes

# FRONT-END (Angular/React TypeScript)

sonar.sources+=,front/src
sonar.tests+=,front/src/app
sonar.language=ts
sonar.typescript.lcov.reportPaths=front/coverage/lcov.info
