# ================================
# Projet
# ================================
sonar.projectKey=Nesesan_Projet_OC10
sonar.organization=nesesan
sonar.host.url=https://sonarcloud.io
sonar.projectBaseDir=.

# ================================
# Front-end
# ================================
sonar.sources.front=front/src
sonar.tests.front=front/src
sonar.test.inclusions.front=**/*.spec.ts
sonar.exclusions.front=**/node_modules/**
sonar.javascript.lcov.reportPaths.front=front/coverage/bobapp/lcov.info

# ================================
# Back-end
# ================================
sonar.sources.back=back/src/main/java
sonar.tests.back=back/src/test/java
sonar.java.binaries=back/target/classes
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
