# ================================
# Projet
# ================================
sonar.projectKey=Nesesan_Projet_OC10
sonar.organization=nesesan
sonar.host.url=https://sonarcloud.io
sonar.projectBaseDir=.

# ================================
# Sources & Tests
# ================================
sonar.sources=front/src,back/src/main/java
sonar.tests=front/src,back/src/test/java
sonar.test.inclusions=**/*.spec.ts,**/*Test.java
sonar.exclusions=**/node_modules/**

# ================================
# Coverage
# ================================
sonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info
sonar.java.binaries=back/target/classes
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
