sonar.projectKey=Nesesan_Projet_OC10
sonar.organization=nesesan
sonar.host.url=https://sonarcloud.io

# ============ BACK-END ============
sonar.java.binaries=back/target/classes

# ============ FRONT-END ============
sonar.sources=front/src,back/src/main/java
sonar.tests=front/src,back/src/test/java
sonar.exclusions=**/node_modules/**,**/*.spec.ts
sonar.test.inclusions=**/*.spec.ts,**/*Test.java

# Coverage (front + back)
sonar.javascript.lcov.reportPaths=front/coverage/lcov.info
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
