name: CI/CD Build

on:
  push:
    branches: ["main", "develop"]
  workflow_dispatch:

jobs:
  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 18
      - run: npm ci
        working-directory: ./front
      - run: npm run build
        working-directory: ./front
      - name: Upload front build
        uses: actions/upload-artifact@v4
        with:
          name: front-build
          path: ./front/dist
          retention-days: 3  # garde l'artefact disponible 3 jours

  build-back:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: 11
        - run: mvn -B clean verify
          working-directory: ./back
        - name: Upload back build
          uses: actions/upload-artifact@v4
          with:
            name: back-build
            path: ./back/target
            retention-days: 3  #garde l'artefact disponible 3 jours