name: CI/CD Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # Front-end

      # Node.js setup
      - name: Set up Node.js
        uses: actions/setup-node@v5 #@v5 latest version for setup-node
        with:
          node-version: 18

      - name: Confirm Setup
        run: echo "Checkout and Node.js setup completed"

      # Cache Node modules
      - name: Cache Node modules
        uses:  actions/cache@v3
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('front/package-lock.json') }}

      # Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: ./front

      # Build front-end
      - name: Build front-end
        run: npm run build
        working-directory: ./front

      # Run tests
      - name: Run front-end tests
        run: npm run test -- --watch=false --code-coverage
        working-directory: ./front

      # Confirm step success
      - name: Confirm front-end success
        run: echo "Front-end build and tests completed"
