name: Docker Build and Push

on:
  workflow_run:
    workflows: [ "CI Tests and Sonar" ]
    types:
      - completed

jobs:

  # Login Docker
  login_docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

  # Build & push frontend
  build_front_and_push:
    needs: login_docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & push Front image
        run: |
          docker build -t bobapp-front ./front
          docker tag bobapp-front "${{ secrets.DOCKER_USERNAME }}/bobapp-front:${{ github.event.workflow_run.head_sha }}"
          docker tag bobapp-front "${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest"
          docker push "${{ secrets.DOCKER_USERNAME }}/bobapp-front:${{ github.event.workflow_run.head_sha }}"
          docker push "${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest"

  # Build & push backend
  build_back_and_push:
    needs: login_docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & push Back image
        run: |
          docker build -t bobapp-back ./back
          docker tag bobapp-back "${{ secrets.DOCKER_USERNAME }}/bobapp-back:${{ github.event.workflow_run.head_sha }}"
          docker tag bobapp-back "${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest"
          docker push "${{ secrets.DOCKER_USERNAME }}/bobapp-back:${{ github.event.workflow_run.head_sha }}"
          docker push "${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest"
