name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:


  # Login Docker
  login_docker:
    runs-on: ubuntu-latest
    outputs:
      docker_logged_in: ${{ steps.login.outputs.success }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        id: login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          echo "success=true" >> $GITHUB_OUTPUT


  # Build & push Front image
  build_front_and_push:
    needs: login_docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build & push Front image
        run: |
          docker build -t bobapp-front ./front
          docker tag bobapp-front "${{ secrets.DOCKER_USERNAME }}/bobapp-front:${{ github.sha }}"
          docker tag bobapp-front "${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest"
          docker push "${{ secrets.DOCKER_USERNAME }}/bobapp-front:${{ github.sha }}"
          docker push "${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest"


  # Build & push Back image
  build_back_and_push:
    needs: login_docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build & push Back image
        run: |
          docker build -t bobapp-back ./back
          docker tag bobapp-back "${{ secrets.DOCKER_USERNAME }}/bobapp-back:${{ github.sha }}"
          docker tag bobapp-back "${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest"
          docker push "${{ secrets.DOCKER_USERNAME }}/bobapp-back:${{ github.sha }}"
          docker push "${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest"
