name: Tests + Quality Pipeline

on:
  workflow_run:
    workflows: ["CI/CD Build"]
    types:
      - completed

jobs:
  tests-and-sonar:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Setup environments
      - uses: actions/setup-node@v5
        with:
          node-version: 18
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Front-end tests
      - run: npm ci
        working-directory: ./front
      - run: npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless
        working-directory: ./front

      # Back-end tests + Jacoco
      - run: mvn test jacoco:report
        working-directory: ./back

      # Build back-end (nécessaire pour Sonar)
      - run: mvn -B clean verify
        working-directory: ./back

      # Install Sonar Scanner
      - run: npm install -g sonar-scanner

      # Run SonarCloud Analysis
      - env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: sonar-scanner
