name: Tests and Quality Pipeline

on:
  workflow_run:
    workflows: ["CI/CD Build"]
    types:
      - completed

jobs:
  tests-and-sonar:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ FRONT-END tests + coverage
      - uses: actions/setup-node@v5
        with:
          node-version: 18

      - name: Install front dependencies
        run: npm ci
        working-directory: ./front

      - name: Run front-end tests with coverage
        run: npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless
        working-directory: ./front

      - name: Debug coverage file
        run: find front -name "lcov.info" -print

      # 3️⃣ BACK-END tests + Jacoco
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Run backend tests with Jacoco
        run: mvn clean verify jacoco:report
        working-directory: ./back

      - name: Debug Jacoco
        run: find back -name "jacoco.xml" -print

      # 4️⃣ SonarCloud Analysis
      - name: Install Sonar Scanner
        run: npm install -g sonar-scanner

      - name: Inspect lcov file before Sonar
        run: |
          echo "=== Vérif du fichier lcov.info ==="
          ls -lh front/coverage/bobapp/lcov.info || echo "Pas trouvé"
          echo "=== Nombre de lignes ==="
          wc -l front/coverage/bobapp/lcov.info || true
          echo "=== Extrait (10 premières lignes) ==="
          head -n 10 front/coverage/bobapp/lcov.info || true
      

      - name: Run SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # -------------------------------
      # Re-upload artifacts for Docker
      # -------------------------------
      - name: Download front build from CI/CD
        uses: actions/download-artifact@v4
        with:
          name: front-build
          path: ./front/dist

      - name: Download back build from CI/CD
        uses: actions/download-artifact@v4
        with:
          name: back-build
          path: ./back/target

      - name: Re-upload front build for Docker
        uses: actions/upload-artifact@v4
        with:
          name: front-build
          path: ./front/dist
          retention-days: 2

      - name: Re-upload back build for Docker
        uses: actions/upload-artifact@v4
        with:
          name: back-build
          path: ./back/target
          retention-days: 2