name: Tests and Quality Pipeline

on:
  workflow_run:
    workflows: ["CI/CD Build"]
    types:
      - completed

jobs:
  tests-and-sonar:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node.js
      - uses: actions/setup-node@v5
        with:
          node-version: 18

      # Front-end tests
      - run: npm ci
        working-directory: ./front
      - run: npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless
        working-directory: ./front

      # Setup Java
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Back-end tests + Jacoco
      - run: mvn test jacoco:report
        working-directory: ./back

      # Install Sonar Scanner
      - run: npm install -g sonar-scanner

      # Run SonarCloud Analysis
      - env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }}
