name: Tests and Quality Pipeline

on:
  workflow_run:
    workflows: ["CI/CD Build"]
    types:
      - completed

jobs:
  tests-and-sonar:
    runs-on: ubuntu-latest

    steps:

      # Checkout repository

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      # Setup Node.js (Front-end)

      - uses: actions/setup-node@v5
        with:
          node-version: 18


      # Front-end tests + coverage

      - name: Install front dependencies
        run: npm ci
        working-directory: ./front

      - name: Run front-end tests with coverage
        run: npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless
        working-directory: ./front

      - name: Debug front coverage
        run: ls -lah front/coverage/bobapp || echo "Pas de coverage front"


      # Setup Java (Back-end)

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17


      # Build + Tests Back-end (Jacoco)

      - name: Run back-end tests + Jacoco
        run: mvn clean verify jacoco:report
        working-directory: ./back

      - name: Debug back coverage
        run: ls -lah back/target/site/jacoco || echo "Pas de coverage back"


      # Upload coverage artifacts

      - name: Upload Front Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: front-coverage-report
          path: front/coverage/bobapp/

      - name: Upload Back Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: back-jacoco-report
          path: back/target/site/jacoco/


      # Install Sonar Scanner

      - name: Install Sonar Scanner
        run: npm install -g sonar-scanner


      # Run SonarCloud Analysis


      - name: Debug front coverage path
        run: find . -type f -name "lcov.info"

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "=== Contenu du dossier target/classes ==="
          ls -lah back/target/classes || echo "Pas trouvé !"
          echo "=== Contenu du dossier jacoco ==="
          ls -lah back/target/site/jacoco || echo "Pas trouvé !"
          sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }}
